export {
  LnExplorerClient,
  createClient,
  type ClientOptions,
  type EgoGraphOptions,
} from './client.js';

export { RobtexValidationError, parseResponse, tryParseResponse } from './validate.js';

export { buildEgoGraph, type EgoGraph, type EgoNode, type EgoLink } from './ego.js';

export type {
  ApiStatus,
  ApiError,
  Pagination,
  LightningChannelSummary,
  LightningChannel,
  LatestLightningChannelsResponse,
  LightningNode,
  LightningNodeSummary,
  RecommendedPeer,
  RecommendedPeersResponse,
  SearchNodesResponse,
  ChannelsPerNodeResponse,
  BitcoinAddressType,
  BitcoinAddressInfo,
  BitcoinAbuseInfo,
  BitcoinAddressResponse,
  BitcoinTxInput,
  BitcoinTxOutput,
  BitcoinTransaction,
  BitcoinTransactionResponse,
  BitcoinAddressTxSummary,
  BitcoinAddressTransactionsResponse,
  BitcoinSpendOutput,
  BitcoinTransactionSpendsResponse,
  BitcoinBlock,
  BitcoinBlockResponse,
  PingResponse,
} from './schemas.js';

export {
  PaginationSchema,
  ApiErrorSchema,
  LightningChannelSummarySchema,
  LightningChannelSchema,
  LatestLightningChannelsResponseSchema,
  LightningNodeSchema,
  LightningNodeSummarySchema,
  RecommendedPeerSchema,
  RecommendedPeersResponseSchema,
  SearchNodesResponseSchema,
  ChannelsPerNodeResponseSchema,
  BitcoinAddressInfoSchema,
  BitcoinAbuseInfoSchema,
  BitcoinAddressResponseSchema,
  BitcoinTxInputSchema,
  BitcoinTxOutputSchema,
  BitcoinTransactionSchema,
  BitcoinTransactionResponseSchema,
  BitcoinAddressTxSummarySchema,
  BitcoinAddressTransactionsResponseSchema,
  BitcoinSpendOutputSchema,
  BitcoinTransactionSpendsResponseSchema,
  BitcoinBlockSchema,
  BitcoinBlockResponseSchema,
  PingResponseSchema,
} from './schemas.js';
